name: "[CD] continuous delivery"

on: 
  push: 
    branches: 
      [main] 
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  

jobs:
  deploy-on-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: debug
        run: |
          ls -la

      - name: install dependencies
        run: npm ci 

      - name: deploy
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}


